### PR TITLE
support for Snowflake - upgrade from previous 5.0.7-based PR

### PR DESCRIPTION
**Pull request by brianrepko**
This PR upgrades the work from @billwanjohi on #1914 to v5.2.4.

I'm still in the process of testing it

### CODE REVIEW

**Comment by brianrepko** [comment]
testing is complete on our side - just noticed that `clean` was generating the wrong SQL

**Comment by AshkanK** [comment]
Eagerly waiting for this merge into master. Thanks for a great work @brianrepko

**Comment by caseylargent** [comment]
Will this be merged soon? My company is eagerly looking at using this for our Snowflake environment

**Comment by billwanjohi** [comment]
Unfortunately this is unlikely, per @axelfontaine's [comment](https://github.com/flyway/flyway/pull/1914#issuecomment-393198839) on a previous pull request:

> At this point we would probably need some kind of commercial agreement to account for our testing, maintenance, documentation and support costs. Please get in touch if your company is willing to explore options.

The PR itself is useful as an advertisement to others of a snowflake-compatible fork, but until Flyway changes strategy, don't hold your breath about it getting merged.

**Comment by brianrepko** [comment]
Looks like I might have to upgrade this to the 6.0 beta (not sure how much has changed). However, I'm sure that someone from Snowflake could make this work / upgrade it (they do have engineers) and / or they could provide credits to test this out. It's not that difficult really with a cloud-based database.

**Comment by apunhiran** [comment]
Eagerly waiting for this to be available.

**Review by koundinyagoparaju — APPROVED** [review]

**Comment by Riteshmshukla** [comment]
I work with snowflake and would like to use flyway for the versioning.  how do I install flyway from this branch?

**Comment by billwanjohi** [comment]
You can make yourself a jar with the maven wrapper script in this repository. Flyway doesn't have their own instructions for this, but you can get some general guidance from [this readme](https://github.com/takari/maven-wrapper/blob/master/README.md).

**Comment by Riteshmshukla** [comment]
thank you @billwanjohi. I will give it a try.

**Comment by mwessman** [comment]
Is there any timeline for when this might be officially supported?

**Comment by skippyabroad** [comment]
Thanks to all contributors on this. Snowflake biggest up-tick on DBEngines top 100 last month and second behind Presto for the past year.

**Comment by juliahayward** [comment]
This PR is probably redundant now as we're working on building Snowflake support into v6.1 .

**Comment by juliahayward** [comment]
I'm going to close this - 6.1 will be out with Snowflake support next week. Thanks to everyone who contributed!

**Pull request closed without merging**
