### PR TITLE
Support S3 locations

### PR DESCRIPTION
**Pull request by JonLally**
Support s3 locations by use of aws-java-sdk-s3.

Issue references: #1961  #1779 

- I'm not 100% sure of some of the changes I made, specifically the entry in the flyway-core pom for the maven bundle plugin. 
- I also had to explicitly specify 4.5.2 version of the httpclient from apache http components, it is a transitive dependency of aws-java-sdk-s3 and updating the order of the dependencies didn't matter as it took the version from google android always.
- I'm unsure of the testing process, I've had to manually test this but if there is an automated suite I can contribute to I'd like to provide tests around this functionality.

### CODE REVIEW

**Comment by KiruthikaSS** [comment]
Eager to know, when this feature will be released. Any Milestone planned? Plz let me know.

**Comment by juliahayward** [comment]
Many thanks for the contribution (and welcome to the hall of fame!) We're looking at including this by 6.3 - including tests at our end and documentation changes.

**Comment by juliahayward** [comment]
Do have a look at https://github.com/flyway/flyway/issues/2664 - this came up with both AWS SDK 1.11 and 2.0. We would strongly prefer to use the v2 SDK (which requires some code changes, although they are pretty mechanical and I have done them) however that requires Java 8 - any thoughts?
.

**Comment by JonLally** [comment]
Wasn't aware of the AWS SDK v2, would definitely agree with using it instead of 1.1.

**Comment by Lyeeedar** [comment]
Moving this to flyway 7.x as the v2 SDK requires upgrading flyway from java 7. See https://github.com/flyway/flyway/pull/2458#issuecomment-582872908

**Pull request closed without merging**
