### PR TITLE
Fix update checksum query for Phoenix. Resolves #1262

### LINKED ISSUE #1262: Unit test failing for Phoenix DB support
###### What version of Flyway are you using?

Flyway version 4.0
###### What database are you using (type & version)?

Phoenix - 4.6
###### What operating system are you using?

Mac OS X
###### What did you do?

(Please include the content causing the issue, any relevant configuration settings, and the command you ran)

Running the PhoenixMigrationMediumTest, when trying to build flyway with a particular version of Phoenix. Command used from the **flyway-core** module,
**mvn clean install -P-InstallableDBTest -P-CommercialDBTest -P-CommandlinePlatformAssemblies -PPhoenixDBTest -Dmaven.failsafe.debug -Dmaven.surefire.debug -Dtest=PhoenixMigrationMediumTest#repairChecksum**
###### What did you expect to see?

Build should pass successfully.
###### What did you see instead?

Build failed with the error,
`Running org.flywaydb.core.internal.dbsupport.phoenix.PhoenixMigrationMediumTest
Tests run: 1, Failures: 0, Errors: 1, Skipped: 0, Time elapsed: 306.38 sec <<< FAILURE! - in org.flywaydb.core.internal.dbsupport.phoenix.PhoenixMigrationMediumTest
repairChecksum(org.flywaydb.core.internal.dbsupport.phoenix.PhoenixMigrationMediumTest)  Time elapsed: 306.38 sec  <<< ERROR!
org.flywaydb.core.api.FlywayException: Unable to update checksum in metadata table "schema_version" for version 1 to -84236181`

This seems to happen because the **schema_version** table in Phoenix is created using the script,

> -- Create table
> CREATE TABLE "${schema}"."${table}" (
>     "version" VARCHAR(50),
>     "installed_rank" INTEGER NOT NULL PRIMARY KEY,
>     "description" VARCHAR(200),
>     "type" VARCHAR(20),
>     "script" VARCHAR(1000),
>     "checksum" INTEGER,
>     "installed_by" VARCHAR(100),
>     "installed_on" TIMESTAMP,
>     "execution_time" INTEGER,
>     "success" BOOLEAN
> );

But the update checksum script is,

> -- Update checksum for a version
> UPSERT INTO "${schema}"."${table}" (
>     "version",
>     "checksum"
> ) VALUES (
>      '${version_val}',
>      ${checksum_val}
> );

### PR DESCRIPTION
**Pull request by jmahonin**
Re-work the updateChecksum.sql for Phoenix to work with the modified table schema.

### CODE REVIEW

**Comment by axelfontaine** [comment]
This is incorrect as it does not deal with repeatable migrations where version is null.

**Comment by anirudha13** [comment]
@axelfontaine you are right. What is the scenario where the checksum of a repeatable migration needs to be updated without the re-application of the migration?

**Comment by axelfontaine** [comment]
Flyway.repair() comes to mind even though I must admit it doesn't make as much sense as for versioned ones. Nevertheless it shouldn't be too hard to implement a fix that works.

**Comment by jmahonin** [comment]
Would that scenario work with the regular code path?

https://github.com/flyway/flyway/blob/master/flyway-core/src/main/java/org/flywaydb/core/internal/metadatatable/MetaDataTableImpl.java#L389-L390

Is there an existing unit test somewhere for that scenario I can use as a reference? I'd like to get this resolved ASAP, but am being pulled in a bunch of different directions at the moment. Any suggestions or help here would be appreciated.

**Pull request closed without merging**
