### PR TITLE
Introduce skipDefaultResolvers property

### PR DESCRIPTION
**Pull request by pauxus**
This allows to completely skip the usage of the built-in resolvers and thus only rely on custom resolvers.

### CODE REVIEW

**Comment by axelfontaine** [comment]
Thanks! Much better!

Don't forget Ant. Also I believe the SBT support isn't complete yet as the values aren't passed from the settings to the other objects.

**Comment by pauxus** [comment]
Ant: implemented (missed that one).
I hope I have everything covered in SBT now. I did not get my Scala environment working to make sure, could you please take a look?

**Comment by axelfontaine** [comment]
Thanks. Merged. Please look at the additional commit I made. These are important things for next time. Docs aren't much fun to write, but they are essential for making Flyway a joy to use.

Cheers
Axel

P.S.: Looking forward to the flywaydb.org (flyway-4.0 branch) PR for the docs.

**Comment by pauxus** [comment]
Ok, you were faster, you have already included relevant changes in the website. Anything still open there? 

FYI: I am currently updating Javadocs as well as the website concerning the ConfigurationAware PR.

**Comment by axelfontaine** [comment]
No, the changes I have include are for skipDefaultCallbacks...

**Comment by pauxus** [comment]
Ups, sorry...

**Comment by pauxus** [comment]
done: https://github.com/flyway/flywaydb.org/pull/55

**Pull request merged**
