### PR TITLE
Add snowflake support to v5

### PR DESCRIPTION
**Pull request by billwanjohi**
This revives the work @alexlevene did to add [Snowflake](https://github.com/snowflakedb/snowflake-jdbc) support to Flyway 4.x in #1776, now rebased and revised to work with the 5.0.7 tag.

The main differences are that the previous branch has tests that no longer have a place here, and the SnowflakeDbSupport class was split into a database and a connection.

We're using this internally without issue.

### CODE REVIEW

**Comment by billwanjohi** [comment]
Hi @axelfontaine, can you elaborate on the "someday-maybe" classification? Is there a checklist of additional contributions that we need to make before it's suitable for inclusion? Is there an alternative means to use flyway with other databases other than forking the main repository?

**Comment by cladden** [comment]
@axelfontaine aside from a rebase to master, is there something else blocking acceptance of this PR?

**Comment by axelfontaine** [comment]
@cladden The biggest issue is https://db-engines.com/en/ranking , which effectively means that until popularity increases this will mean a lot maintenance cost to support a comparatively very small group of users.

**Comment by jwnorma** [comment]
Would love to see this merged in.  We use flyway in several other projects, would be great to have consistency with snowflake as well.  


The DB-Engines ranking is a lagging indicator, and adoption of Snowflake is on the rise.

**Comment by countergram** [comment]
Wondering the same - is there any kind of plugin system to support this without the merge? Otherwise what will it take to get this merged?

**Comment by christippett** [comment]
Similar to @countergram, I also wondered if adding a plugin system for databases could be a good idea -- especially given the number of feature/pull requests asking for specific database support.

Rather than having to fork the Flyway core, adding a classpath to the configuration file for third-party database support could be a happy compromise. Is it worth raising this as a feature request?

**Comment by h8** [comment]
Anu updates on merging Snowflake support branch?

**Comment by DjShinndig** [comment]
Snowflake support would be AWESOME

**Comment by kulmam92** [comment]
Any plan to fix error and merge this?
It will be a helpful change

**Comment by brianrepko** [comment]
Just adding a note to say that we gave up trying to support Snowflake with Liquibase and are now looking at this too - thanks to all for your previous work - I'll be testing this out as well. I'm on gitter as well for IM.

**Comment by vepetkov** [comment]
It would be really great if this feature can finally get merged. Are there any specific timeline about that?

**Comment by brianrepko** [comment]
I just created the PR for the upgrade of this code to 5.2.4. Word of warning - we are currently just testing this.

**Comment by AshkanK** [comment]
Eagerly waiting for this merge into master. Thanks for a great work @brianrepko

**Comment by billwanjohi** [comment]
Closing this because it's stale, I don't currently use the flyway/snowflake combo, and there exists a newer PR for the same functionality (#2274). I'll keep my fork alive if anyone wants the commits.

**Comment by brianrepko** [comment]
Thank you @billwanjohi - this work was invaluable!!!!

**Comment by bobtiernay-okta** [comment]
> Rather than having to fork the Flyway core, adding a classpath to the configuration file for third-party database support could be a happy compromise. Is it worth raising this as a feature request?

@christippett  I agree this is the way to go. The current issue are the static binding to the provided dbs. It would be great to a have more dynamic mechanism to register dbs instead of having to fork.

**Comment by bobtiernay-okta** [comment]
> The biggest issue is https://db-engines.com/en/ranking , which effectively means that until popularity increases this will mean a lot maintenance cost to support a comparatively very small group of users.

What is an acceptable ranking? Snowflake seems to be quickly moving up and likely will continue the trend due to its impressive adoption.

**Pull request closed without merging**
