### PR TITLE
Allow extending classpath in gradle task config

### PR DESCRIPTION
**Pull request by simschla**
especially to allow for custom `org.gradle.api.artifacts.Configuration` to be used for separating flyway java migrations from other code.

### CODE REVIEW

**Comment by simschla** [comment]
Failing travis build seems unrelated to my change: Fails are in flyway-core...

**Comment by axelfontaine** [comment]
@simschla Please sign the CLA and fix conflicts so this can be merged. Thanks!

**Comment by simschla** [comment]
I'm a bit confused - did you actually **delete** all integration-tests such as the above confliciting GradleLargeTest.java? Or am I just to stupid to find the place in the repo where those things have been moved to?

**Comment by axelfontaine** [comment]
@simschla Could you make this mergeable again so it can be included in 5.1.0? Thanks!

**Comment by simschla** [comment]
@axelfontaine Would love to do that, but am still waiting for your answer to my question above... Are all integration-tests gone? How would I go ahead and test my code in the current setup?

**Comment by axelfontaine** [comment]
@simschla Yes, tests have been removed. We'll test it for you after merging.

**Comment by simschla** [comment]
ready to merge - but please test thoroughly, since I cannot do that on my end.

**Comment by simschla** [comment]
I've added the documentation-pr: https://github.com/flyway/flywaydb.org/pull/96

**Comment by axelfontaine** [comment]
Thanks for the pull requests! Merged! As you can see I ended reworking the code quite a bit to allow for a more generic declarative specification of configurations.

P.S.: I also added you to the hall of fame page (flyway-5.1.0 branch).

**Comment by simschla** [comment]
Thanks for merging. I like your extensions to my extension-pullrequest ;-)
All the best with the upcoming release 5.1.0!

**Pull request merged**
