### PR TITLE
Support for Teradata database

### PR DESCRIPTION
**Pull request by lecaillon**
## Motivation:
This PR aims to add support of Teradata database to Flyway. #1360 

## Context:
Teradata is a fairly standard database but like all others has its specificities.

- Teradata does not have the notion of schema.
- Teradata has a very convenient built-in SQL statement to clean a database (DELETE DATABASE).
- Teradata does not support rollback for DDL statements.
- Moreover, inside a transaction, the JDBC driver throws an exception if any statement (SQL or DDL) is found after a DDL statement.
SQLException : [Teradata Database] [TeraJDBC] [Error 3932] [SQLState 25000] Only an ET or null statement is legal after a DDL Statement.
**In order to manage this specific behavior, Flyway will not wrap the migration in a transaction if any DDL statements is found in the file.**

## Tests:
I use the VMware image of a Teradata Express 15.0 available at http://downloads.teradata.com/download/database/teradata-express-for-vmware-player
The test ensures that mixing transactional and non-transactional statements within the same migration works.
It is really the only difficulty I had to manage.

Looking forward to your feedback.

### CODE REVIEW

**Comment by camory** [comment]
Hello

I am very interesting by this PR. I am using Teradata and wanted to use Flyway to manage the sql migration with Flyway. Do have you any plan when this PR will be merged ?

**Comment by axelfontaine** [comment]
@lecaillon Could you sign the CLA?

**Comment by lecaillon** [comment]
@axelfontaine CLA signed

**Comment by camory** [comment]
@lecaillon 
Tanks 😃

**Comment by camory** [comment]
@axelfontaine, Any plan for merging this PR ?

**Comment by axelfontaine** [comment]
@camory This is the main cause for delaying the merge: https://github.com/flyway/flyway/issues/1360#issuecomment-376153256

**Comment by PhilippeDupont** [comment]
Any update about this PR ?

**Comment by othmaneH9** [comment]
Any news about this PR ?

**Comment by adrianyorke** [comment]
Wow, this is cool - thank you @lecaillon.  Would you be able to sign the CLA and address the merge conflicts?  I can help with further testing and development if you are interested.  I have working Teradata 15 & 16 VMs which I have used on other FOSS project work.

**Comment by schupp** [comment]
Hi Guys, what's the status on the PR? We would also be very interested in using Flyway with Teradata.

**Comment by Crudelis-rgb** [comment]
Hi there!
Whats the Status of the PR? 
It would be great to implement Flyway at our warehouse.
Best, Matthias

**Comment by piers-williams** [comment]
Thank you for your submission. We cannot merge this at this time as it would need re-implementing in the [https://github.com/flyway/flyway-community-db-support](https://github.com/orgs/red-gate/projects/71/views/flyway-community-db-support) repository.

**Pull request closed without merging**
