### PR TITLE
Fixes #2193: PostgreSQL 11.0 is not supported (clean() fails)

### LINKED ISSUE #2193: PostgreSQL 11.0 is not supported (clean() fails)
###### Which version and edition of Flyway are you using?

Flyway Community Edition 5.2.1.

###### Which client are you using? (Command-line, Java API, Maven plugin, Gradle plugin)

Java API. Bug most likely affects all versions.

###### Which database are you using (type & version)?

PostgreSQL 11.0 (released 18 October 2018).

Unsurprisingly, Flyway reports that it does not support this version yet: `Flyway upgrade recommended: PostgreSQL 11.0 is newer than this version of Flyway and support has not been tested.`

###### Which operating system are you using?

Not relevant.

###### What did you do?

I attempted to clean a configured schema using the `Flyway.clean()` method. The `Flyway` instance can connect fine and `Flyway.migrate()` appears to work successfully. 

###### What did you expect to see?

The schema is cleaned in the database and `Flyway.clean()` doss not throw an exception.

###### What did you see instead?

The database does not appear to be modified. `Flyway.clean()` throws a `FlywaySqlException`:

```
org.flywaydb.core.internal.exception.FlywaySqlException:
Unable to clean schema "public"
-------------------------------
SQL State  : 42703
Error Code : 0
Message    : ERROR: column pg_proc.proisagg does not exist
  Hint: Perhaps you meant to reference the column "pg_proc.prolang".
  Position: 54

      at org.flywaydb.core.internal.database.base.Schema.clean(Schema.java:151)
      at org.flywaydb.core.internal.command.DbClean$3.call(DbClean.java:172)
      at org.flywaydb.core.internal.command.DbClean$3.call(DbClean.java:169)
      at org.flywaydb.core.internal.jdbc.TransactionTemplate.execute(TransactionTemplate.java:74)
      at org.flywaydb.core.internal.command.DbClean.cleanSchema(DbClean.java:169)
      at org.flywaydb.core.internal.command.DbClean.clean(DbClean.java:113)
      at org.flywaydb.core.Flyway.doClean(Flyway.java:1473)
      at org.flywaydb.core.Flyway.access$300(Flyway.java:82)
      at org.flywaydb.core.Flyway$3.execute(Flyway.java:1491)
      at org.flywaydb.core.Flyway$3.execute(Flyway.java:1484)
      at org.flywaydb.core.Flyway.execute(Flyway.java:1696)
      at org.flywaydb.core.Flyway.clean(Flyway.java:1484)
```

###### Notes

PostgreSQL 11.0's [release notes](https://www.postgresql.org/docs/11/static/release-11.html) state the following:

> Replace system catalog pg_proc's proisagg and proiswindow columns with prokind (Peter Eisentraut)
>
> This new column more clearly distinguishes functions, procedures, aggregates, and window functions.

I believe the offending line of code can be found [here](https://github.com/flyway/flyway/blob/e3c9adaac18f46017ad524cbe0df26d13ab33c00/flyway-core/src/main/java/org/flywaydb/core/internal/database/postgresql/PostgreSQLSchema.java#L191). The docs for the new `prokind` field are [here](https://www.postgresql.org/docs/11/static/catalog-pg-proc.html). Fixing this will require the query to be made dependent on the version of PostgreSQL somehow.

I will submit a PR to fix this issue.

### PR DESCRIPTION
**Pull request by tinybarks**
Fixes #2193.

I don't see any other changes in PostgreSQL 11.0 that would break compatibility, but please check before merging.

### CODE REVIEW

**Comment by axelfontaine** [comment]
Thanks for the pull request! Truly appreciated. This will be integrated in 6.0.

**Comment by ieugen** [comment]
Hi, 

Why not back port-it to the 5.x branch? The fix seems simple. I've also checked the issues for 6.x and it doesn't look like it will be released very soon. Any ETA for that? 
/Eugen

**Comment by axelfontaine** [comment]
@ieugen Support for new database versions is only added in major and minor releases, not patch releases. Until [6.0.0](https://github.com/flyway/flyway/milestone/19) is released, you can simply build Flyway from source to get it.

**Comment by ieugen** [comment]
Ok. Thnks for explaining.

**Pull request merged**
