### PR TITLE
Spanner support with Open Source JDBC driver

### PR DESCRIPTION
**Pull request by stankiewicz**
Hi,
Due to open sourcing Spanner driver and it's better support for DML and DDL it is possible to integrate it with flyway. 
There are still things not supported like transactional ddl/dml.
Also due to the fact that information schema needs read only connection I had to use raw connection instead of jdbcTemplate. 

please take a look.

### CODE REVIEW

**Comment by stankiewicz** [comment]
this PR should replace #1880  done by @olavloite . #1880 was done using unofficial driver.

**Comment by thinhha** [comment]
+1 this is very much needed.

**Comment by stankiewicz** [comment]
@MikielAgutu , would you be able to take a look at this?

**Comment by MikielAgutu** [comment]
@stankiewicz Thanks for the contribution! The new JDBC driver certainly provides more confidence this would be a stable addition to Flyway.

Because this is a cloud database, it's more difficult for us to set up automated testing + CI processes to maintain a high level of stability. We'll need some time to decide internally if this is the right direction for Flyway.

We acknowledge this is a popular DB and we are pleased that the community has done so much work to contribute support for it.

**Comment by stankiewicz** [comment]
Hi @MikielAgutu , thank you for putting it on radar - Spanner have emulator. 
If you have requirements somewhere how it is tested then I'm more then happy to contribute in this area.

**Comment by stankiewicz** [comment]
@MikielAgutu , I have created new PR (#2776) due to the fact that this PR had very old changes, binary (jar) commit and it was impossible to squash..

**Pull request closed without merging**
