### PR TITLE
added support for non-transactional SQL migrations

### LINKED ISSUE #1026: support non transactional migrations in SQL api
support for this was added in #655, exposing it to the sql api is pending

I will send a PR for this

### PR DESCRIPTION
**Pull request by Omie**
fixes #1026 
- added new Resolver and Executor classes
- NTSqlMigrationResolver works on the files prefixed with "NTV", currently hardcoded. (Looking forward for suggestions over this)
- Added the new resolver in migrationResolvers while creating CompositeMigrationResolver instance
- added small test for new resolver

### CODE REVIEW

**Comment by ccouturi** [comment]
+1 for this feature.

**Comment by eemmiirr** [comment]
+1

**Comment by Nthalk** [comment]
+1

**Comment by 0x6e6562** [comment]
+1

**Comment by baekdahl** [comment]
+1

**Comment by CRegenschein** [comment]
+1

**Comment by CRegenschein** [comment]
when will this feature be merged into flyway?

**Comment by 0x6e6562** [comment]
For anybody that is looking for a quick and dirty way to mix in some non-transcational migrations into an existing SQL-based patch series, I knocked out the following shim:

```
public abstract class AbstractResolvedMigration implements ResolvedMigration {

  private final String version;
  private final String description;

  public AbstractResolvedMigration() {

    String className = this.getClass().getSimpleName();
    String template = "V(\\d+)__(.*)";
    Pattern pattern = Pattern.compile(template);
    Matcher matcher = pattern.matcher(className);
    if (matcher.matches()) {
      this.version = matcher.group(1);
      this.description = matcher.group(2).replaceAll("_", " ");
    } else {
      throw new RuntimeException("Bogus migration name: " + className);
    }

  }

  @Override
  public MigrationVersion getVersion() {
    return MigrationVersion.fromVersion(version);
  }

  @Override
  public String getDescription() {
    return description;
  }

  @Override
  public Integer getChecksum() {
    final CRC32 crc32 = new CRC32();
    crc32.update(getScript().getBytes());
    return (int) crc32.getValue();
  }

  @Override
  public MigrationType getType() {
    return MigrationType.CUSTOM;
  }

  @Override
  public String getPhysicalLocation() {
    return "virtual://loaction";
  }

  @Override
  public MigrationExecutor getExecutor() {
    return new MigrationExecutor() {

      @Override
      public void execute(Connection connection) {
        PreparedStatement stmt;
        try {
          stmt = connection.prepareStatement(getScript());
          stmt.execute();
        } catch (SQLException e) {
          throw new RuntimeException(e);
        }
      }

      @Override
      public boolean executeInTransaction() {
        return false;
      }

    };
  }
}
```
And then if I need to execute something outside of a TX, I subclass the base class to supply the patch specific SQL. For example, say I have a V50 SQL migration that requires a new type in Postgres, I create a V49 custom migration that patches the DDL in a non-TX migration in order that the subsequent V50 migration that depends on the new type can execute:

```
public class V49__some_meaningful_description extends AbstractResolvedMigration {

  @Override
  public String getScript() {
    return "ALTER TYPE foo ADD VALUE 'BAR' AFTER 'BAZ';";
  }

}
```

And then to mix the V49 migration into the execution series, you need to add a bit of resolver glue and then tell Flyway about it at runtime:

```
public class NonTransactionalMigrationResolver implements MigrationResolver {

  @Override
  public List<ResolvedMigration> resolveMigrations() {

    List<ResolvedMigration> resolvedMigrations = new ArrayList<>();

    resolvedMigrations.add(new V49__some_meaningful_description());
    // add any other non-TX migrations to this list

    return resolvedMigrations;
  }
}
```

Hope this can help somebody until such a time that there is a less hacky way to do this kind of thing.

**Comment by hendley** [comment]
+1

**Comment by eemmiirr** [comment]
+1

**Comment by mjallday** [comment]
:+1:

**Comment by tomdcc** [comment]
+1

@axelfontaine Is there anything we can do to help get this PR in shaped to be merged?

**Comment by akopts** [comment]
+1

**Comment by mr-zhukov** [comment]
+1

**Comment by skrasovsky** [comment]
+1

**Comment by skozlov** [comment]
+1

**Comment by irwinm** [comment]
+1

**Comment by hhware** [comment]
+1

**Comment by brckner** [comment]
When would this feature be merged into master? We have currently issues too, where we need migrations to run in an non transactional context.

**Comment by falschparker82** [comment]
+1

**Comment by karlvlam** [comment]
+1

**Comment by karlvlam** [comment]
any updates for this issue?

**Comment by anthonylau** [comment]
+1

**Comment by VLMH** [comment]
+1

**Comment by jjbubudi** [comment]
+1

**Comment by lukasniemeier-zalando** [comment]
@axelfontaine dies this change has a Chance of being merged?

**Comment by morero** [comment]
+1

**Comment by j-lindblom** [comment]
@axelfontaine Would you consider merging this PR?

**Comment by Trekoid** [comment]
I wouldn't want non-transactional migrations to have a different runtime order than the regular V1_Description.sql files. I would prefer something like V53_NT__Description.sql or V53__NT_Description.sql so they would run in line with other transactional migrations.

**Comment by Omie** [comment]
@Trekoid this patch _does_ maintain the order. V1_foo.sql, NTV2_bar.sql and V3_baz.sql files will get executed in foo, bar, baz order.

On the other note, this PR is vastly out of date, there are hundreds of commits in between and this will probably require work from scratch.

**Comment by davidvuong** [comment]
Hey @Omie,

Just to add to @Trekoid's comment:

My IDE orders files alphanumerically and having it named `NTVxx` when all other flyway migrations are` Vxx` makes it a little hard to navigate. I understand that flyway will run these migrations in order but editors won't display them in order (which can be a bit difficult to grok if you have lots of migrations).

Just my 2 cents. Awesome PR BTW. I'd love to see this *finally* get merged soon.

**Comment by Trekoid** [comment]
@davidvuong your should be happy to hear the company I work for co-sponsored the development of non-transactional migrations with BoxFuse, so expect it soon in release 4.1. The solution @axelfontaine and the team at BoxFuse requires no special file naming. It will auto detect the migration and run it appropriately.

**Comment by davidvuong** [comment]
@Trekoid That awesome. Looking forward to it!

**Comment by brckner** [comment]
Hey, I've also worked on a non transactional resolver for flyway. It scans for sql files with suffix .ntx.sql and executes them in a nontransactional context. It works only with flyway maven plugin... so you can add it as a dependency in maven pom and add the custom resolver in the flyway-maven-plugin. if anyone is interested, i'll put it on gitlab and maven central.

**Comment by arturaz** [comment]
Anything?

**Comment by axelfontaine** [comment]
This has been implemented differently using auto-detection (PostgreSQL only for now). Closing.

**Comment by mohammad-sk** [comment]
@andrewlmurray Pls help
Error starting ApplicationContext. To display the conditions report re-run your application with 'debug' enabled.
2021-03-02 17:21:39.233 ERROR [identity-service,,,] 5621 --- [           main] o.s.boot.SpringApplication               : Application run failed

org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'flywayInitializer' defined in class path resource [org/springframework/boot/autoconfigure/flyway/FlywayAutoConfiguration$FlywayConfiguration.class]: Invocation of init method failed; nested exception is org.flywaydb.core.api.FlywayException: Unable to parse statement in db/migration/V1_1__Identity_Service_dml.sql at line 1 col 1: No value provided for placeholder: ${USER_NAME}.  Check your configuration!
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.initializeBean(AbstractAutowireCapableBeanFactory.java:1796) ~[spring-beans-5.2.4.RELEASE.jar!/:5.2.4.RELEASE]
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:595) ~[spring-beans-5.2.4.RELEASE.jar!/:5.2.4.RELEASE]
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:517) ~[spring-beans-5.2.4.RELEASE.jar!/:5.2.4.RELEASE]
        at org.springframework.beans.factory.support.AbstractBeanFactory.lambda$doGetBean$0(AbstractBeanFactory.java:323) ~[spring-beans-5.2.4.RELEASE.jar!/:5.2.4.RELEASE]
        at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:222) ~[spring-beans-5.2.4.RELEASE.jar!/:5.2.4.RELEASE]
        at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:321) ~[spring-beans-5.2.4.RELEASE.jar!/:5.2.4.RELEASE]
        at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:202) ~[spring-beans-5.2.4.RELEASE.jar!/:5.2.4.RELEASE]
        at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:310) ~[spring-beans-5.2.4.RELEASE.jar!/:5.2.4.RELEASE]
        at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:202) ~[spring-beans-5.2.4.RELEASE.jar!/:5.2.4.RELEASE]
        at org.springframework.context.support.AbstractApplicationContext.getBean(AbstractApplicationContext.java:1108) ~[spring-context-5.2.4.RELEASE.jar!/:5.2.4.RELEASE]
        at org.springframework.context.support.AbstractApplicationContext.finishBeanFactoryInitialization(AbstractApplicationContext.java:868) ~[spring-context-5.2.4.RELEASE.jar!/:5.2.4.RELEASE]
        at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:550) ~[spring-context-5.2.4.RELEASE.jar!/:5.2.4.RELEASE]
        at org.springframework.boot.web.servlet.context.ServletWebServerApplicationContext.refresh(ServletWebServerApplicationContext.java:141) ~[spring-boot-2.2.5.RELEASE.jar!/:2.2.5.RELEASE]
        at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:747) ~[spring-boot-2.2.5.RELEASE.jar!/:2.2.5.RELEASE]
        at org.springframework.boot.SpringApplication.refreshContext(SpringApplication.java:397) ~[spring-boot-2.2.5.RELEASE.jar!/:2.2.5.RELEASE]
        at org.springframework.boot.SpringApplication.run(SpringApplication.java:315) ~[spring-boot-2.2.5.RELEASE.jar!/:2.2.5.RELEASE]
        at org.springframework.boot.SpringApplication.run(SpringApplication.java:1226) ~[spring-boot-2.2.5.RELEASE.jar!/:2.2.5.RELEASE]
        at org.springframework.boot.SpringApplication.run(SpringApplication.java:1215) ~[spring-boot-2.2.5.RELEASE.jar!/:2.2.5.RELEASE]
        at com.bkgaming.bkpoker.service.identity.BKPokerIdentityServiceApplication.main(BKPokerIdentityServiceApplication.java:28) ~[classes!/:sp09-SNAPSHOT]
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:na]
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[na:na]
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:na]
        at java.base/java.lang.reflect.Method.invoke(Method.java:566) ~[na:na]
        at org.springframework.boot.loader.MainMethodRunner.run(MainMethodRunner.java:48) ~[bkpoker-identity-service-sp09-SNAPSHOT.jar:sp09-SNAPSHOT]
        at org.springframework.boot.loader.Launcher.launch(Launcher.java:87) ~[bkpoker-identity-service-sp09-SNAPSHOT.jar:sp09-SNAPSHOT]
        at org.springframework.boot.loader.Launcher.launch(Launcher.java:51) ~[bkpoker-identity-service-sp09-SNAPSHOT.jar:sp09-SNAPSHOT]
        at org.springframework.boot.loader.JarLauncher.main(JarLauncher.java:52) ~[bkpoker-identity-service-sp09-SNAPSHOT.jar:sp09-SNAPSHOT]
Caused by: org.flywaydb.core.api.FlywayException: Unable to parse statement in db/migration/V1_1__Identity_Service_dml.sql at line 1 col 1: No value provided for placeholder: ${USER_NAME}.  Check your configuration!
        at org.flywaydb.core.internal.parser.Parser.getNextStatement(Parser.java:284) ~[flyway-core-6.0.8.jar!/:na]
        at org.flywaydb.core.internal.parser.Parser.access$000(Parser.java:44) ~[flyway-core-6.0.8.jar!/:na]
        at org.flywaydb.core.internal.parser.Parser$ParserSqlStatementIterator.<init>(Parser.java:627) ~[flyway-core-6.0.8.jar!/:na]
        at org.flywaydb.core.internal.parser.Parser.parse(Parser.java:116) ~[flyway-core-6.0.8.jar!/:na]
        at org.flywaydb.core.internal.sqlscript.ParserSqlScript.parse(ParserSqlScript.java:76) ~[flyway-core-6.0.8.jar!/:na]
        at org.flywaydb.core.internal.sqlscript.ParserSqlScript.validate(ParserSqlScript.java:124) ~[flyway-core-6.0.8.jar!/:na]
        at org.flywaydb.core.internal.sqlscript.ParserSqlScript.executeInTransaction(ParserSqlScript.java:187) ~[flyway-core-6.0.8.jar!/:na]
        at org.flywaydb.core.internal.resolver.sql.SqlMigrationExecutor.canExecuteInTransaction(SqlMigrationExecutor.java:75) ~[flyway-core-6.0.8.jar!/:na]
        at org.flywaydb.core.internal.command.DbMigrate.isExecuteGroupInTransaction(DbMigrate.java:312) ~[flyway-core-6.0.8.jar!/:na]
        at org.flywaydb.core.internal.command.DbMigrate.applyMigrations(DbMigrate.java:275) ~[flyway-core-6.0.8.jar!/:na]
        at org.flywaydb.core.internal.command.DbMigrate.migrateGroup(DbMigrate.java:244) ~[flyway-core-6.0.8.jar!/:na]
        at org.flywaydb.core.internal.command.DbMigrate.access$100(DbMigrate.java:54) ~[flyway-core-6.0.8.jar!/:na]
        at org.flywaydb.core.internal.command.DbMigrate$2.call(DbMigrate.java:162) ~[flyway-core-6.0.8.jar!/:na]
        at org.flywaydb.core.internal.command.DbMigrate$2.call(DbMigrate.java:159) ~[flyway-core-6.0.8.jar!/:na]
        at org.flywaydb.core.internal.database.sqlserver.SQLServerApplicationLockTemplate.execute(SQLServerApplicationLockTemplate.java:62) ~[flyway-core-6.0.8.jar!/:na]
        at org.flywaydb.core.internal.database.sqlserver.SQLServerConnection.lock(SQLServerConnection.java:87) ~[flyway-core-6.0.8.jar!/:na]
        at org.flywaydb.core.internal.schemahistory.JdbcTableSchemaHistory.lock(JdbcTableSchemaHistory.java:139) ~[flyway-core-6.0.8.jar!/:na]
        at org.flywaydb.core.internal.command.DbMigrate.migrateAll(DbMigrate.java:159) ~[flyway-core-6.0.8.jar!/:na]
        at org.flywaydb.core.internal.command.DbMigrate.migrate(DbMigrate.java:137) ~[flyway-core-6.0.8.jar!/:na]
        at org.flywaydb.core.Flyway$1.execute(Flyway.java:189) ~[flyway-core-6.0.8.jar!/:na]
        at org.flywaydb.core.Flyway$1.execute(Flyway.java:149) ~[flyway-core-6.0.8.jar!/:na]
        at org.flywaydb.core.Flyway.execute(Flyway.java:511) ~[flyway-core-6.0.8.jar!/:na]
        at org.flywaydb.core.Flyway.migrate(Flyway.java:149) ~[flyway-core-6.0.8.jar!/:na]
        at org.springframework.boot.autoconfigure.flyway.FlywayMigrationInitializer.afterPropertiesSet(FlywayMigrationInitializer.java:65) ~[spring-boot-autoconfigure-2.2.5.RELEASE.jar!/:2.2.5.RELEASE]
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.invokeInitMethods(AbstractAutowireCapableBeanFactory.java:1855) ~[spring-beans-5.2.4.RELEASE.jar!/:5.2.4.RELEASE]
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.initializeBean(AbstractAutowireCapableBeanFactory.java:1792) ~[spring-beans-5.2.4.RELEASE.jar!/:5.2.4.RELEASE]
        ... 26 common frames omitted
Caused by: org.flywaydb.core.api.FlywayException: No value provided for placeholder: ${USER_NAME}.  Check your configuration!
        at org.flywaydb.core.internal.parser.PlaceholderReplacingReader.read(PlaceholderReplacingReader.java:105) ~[flyway-core-6.0.8.jar!/:na]
        at java.base/java.io.FilterReader.read(FilterReader.java:65) ~[na:na]
        at org.flywaydb.core.internal.parser.RecordingReader.read(RecordingReader.java:33) ~[flyway-core-6.0.8.jar!/:na]
        at java.base/java.io.FilterReader.read(FilterReader.java:65) ~[na:na]
        at org.flywaydb.core.internal.parser.PeekingReader.refillPeekBuffer(PeekingReader.java:70) ~[flyway-core-6.0.8.jar!/:na]
        at org.flywaydb.core.internal.parser.PeekingReader.peek(PeekingReader.java:59) ~[flyway-core-6.0.8.jar!/:na]
        at org.flywaydb.core.internal.parser.PeekingReader.peekWhitespace(PeekingReader.java:123) ~[flyway-core-6.0.8.jar!/:na]
        at org.flywaydb.core.internal.parser.PeekingReader.readWhitespace(PeekingReader.java:428) ~[flyway-core-6.0.8.jar!/:na]
        at org.flywaydb.core.internal.parser.Parser.readToken(Parser.java:484) ~[flyway-core-6.0.8.jar!/:na]
        at org.flywaydb.core.internal.parser.Parser.getNextStatement(Parser.java:162) ~[flyway-core-6.0.8.jar!/:na]
        ... 51 common frames omitted

**Pull request closed without merging**
