### PR TITLE
PostgreSQL: Use system catalogs for Table.doExists() & Schema.doEmpty()

### PR DESCRIPTION
**Pull request by RobertRad**
Speed up PostgreSQLTable.doExists()
Also speed up PostgreSQLSchema.doEmpty() - but this is not called as often as the 
former one

Issue:
https://github.com/flyway/flyway/issues/1701 - Table.exists() very slow in Postgres Environments with a lot of objects

### CODE REVIEW

**Comment by RobertRad** [comment]
The built failed (like the current master), because the Travis CI has the line `"jdk": "oraclejdk7",` in it, but Flyway needs Java 8 now.

**Comment by axelfontaine** [comment]
All build issues should now be resolved. Could you sign the CLA to clear the path to merging? Thanks!

**Comment by RobertRad** [comment]
Ok, I signed it.

Maybe you could add the link to the CLA to your contribution guide?

**Comment by axelfontaine** [comment]
Merged. Thanks!

**Pull request merged**
