### PR TITLE
Informix database support

### PR DESCRIPTION
**Pull request by carljmosca**
This is an early attempt at support for the Informix database.

### CODE REVIEW

**Comment by jonathandandries** [comment]
This is great, and it works! Can someone on the dev team please give this a look? Our organization is big into Informix, and this would be a great way to introduce Flyway in house.

**Comment by axelfontaine** [comment]
Thanks for the pull request. I do not believe any of the tests as currently included (copied from the Oracle and MySQL support) do work. Also please no unnecessary reformatting of existing code and no auto-generated IDE placeholder comments to make it easier to evaluate the diff.

Needs major cleanup before being merged.

**Comment by carljmosca** [comment]
axelfontaine, thanks for the reply.  

Can you clarify your comments about reformatting code?  It's hard for me to tell what's preferred as I look at what already exists (i.e. spaces/tabs, inconsistent
indentation in various classes).

How are you connecting to Informix?  Are transactions enabled?  Some of the tests are working but not all of them yet.  As I say in my comment above, it's an early attempt.  (I cannot get all of the Flyway tests to run without the Informix support and I assume I have missed something in the configuration requirements/properties file.)

Any specific hints would be appreciated.

Thanks for your time and effort.

Carl

**Comment by axelfontaine** [comment]
Closing. This has now been implemented differently.

**Pull request closed without merging**
