### PR TITLE
AS400 Support

### PR DESCRIPTION
**Pull request by corneil**
I added as400 support classes.
These classes were based on the DB2 classes with modifications for the way catalogs are managed.

### CODE REVIEW

**Comment by axelfontaine** [comment]
Thanks. As I don't have an AS400 available for testing, would you be willing to support this in the future, should issues come up?

Also could you please submit a pull request against the flyway-4.0 branch of flyway/flywaydb.org with a DB-specific page (like http://flywaydb.org/documentation/database/oracle.html)?

Then we should be good for a speedy merge.

Cheers
Axel

**Comment by axelfontaine** [comment]
Any news?

**Comment by corneil** [comment]
I missed your previous message as I was on leave at the time.
Getting back into things and would probably not get to this in the next few
weeks.




[image: --]
Corneil du Plessis
[image: https://]about.me/corneil
<https://about.me/corneil?promo=email_sig>

**Comment by axelfontaine** [comment]
Closing as we have no plans to add this, as we won't have access to an AS400 for testing in the foreseeable future.

**Pull request closed without merging**
