### PR TITLE
ISSUE 1396: Invite users to use -X switch

### PR DESCRIPTION
**Pull request by logicbomb**
A very simple PR to address issue #1396

### CODE REVIEW

**Comment by axelfontaine** [comment]
This is not the correct place to fix this as -X means nothing to API users for example. This must be addressed generically in the command-line module.

**Comment by logicbomb** [comment]
Oh yes, I see now.  I think this is applicable to all exceptions that are caught by the command line, so I think it makes sense to simply modify `/Users/jason/src/flyway/flyway-commandline/src/main/java/org/flywaydb/commandline/Main.java` Line 108, does that work for you?

**Comment by axelfontaine** [comment]
Yes

**Comment by logicbomb** [comment]
updated

**Comment by axelfontaine** [comment]
Upon second though, I am not entirely happy both with the wording of the message as well as the need for it. For #1396 fixing the original message is probably the better approach.

**Pull request closed without merging**
