### PR TITLE
Fix updateChecksum logic to use installed_rank as well as version. Fixes, #1262.

### PR DESCRIPTION
**Pull request by anirudha13**
Modified the update checksum logic to now use version and installed_rank when updating checksum as part of DB repair.

For ALL of the DBs that flyway supports **installed_rank** is a PRIMARY KEY and cannot be NULL so this should be acceptable (unless I've missed a scenario). This should work for **Repeatable** migrations as well.

Alternative solution to #1263.
Fixes, #1262

@axelfontaine & @jmahonin please review.

### CODE REVIEW

**Comment by jmahonin** [comment]
Changes look good on the Phoenix side. I'll defer to @axelfontaine for comment on the Flway changes.

Thanks @anirudha13

**Comment by anirudha13** [comment]
@axelfontaine please review when you have a chance.

**Comment by anirudha13** [comment]
@axelfontaine any update on this?

**Comment by axelfontaine** [comment]
Sorry about the delay in reviewing this. I just had a look at it and I don't believe this is the desired behavior. By definition the checksum of repeatable migrations can change over time (the checksum change is the trigger that indicates they need to be rerun). Therefore I don't feel it makes sense to update the existing checksums for repeatable migrations as part of a repair operation.

**Comment by anirudha13** [comment]
That's a good point, @axelfontaine. It was my understanding that the version of the repeatable resolved migration would be null. Let me check this once again.

**Comment by jmahonin** [comment]
@anirudha13 Any updates on this? Let me know if I can do anything here.

**Comment by anirudha13** [comment]
@jmahonin sorry was caught up with a couple of things, I need to recreate my dev environment. Target getting to this, sometime this week or early next week.

**Comment by anirudha13** [comment]
@axelfontaine , @jmahonin please re-review the changes. Have added a unit test that ensures that repeatable migrations are not affected.

**Comment by jmahonin** [comment]
LGTM, nice work

**Comment by anirudha13** [comment]
@axelfontaine any chance you could take a look at this next week?

**Comment by anirudha13** [comment]
bump, @axelfontaine

**Comment by axelfontaine** [comment]
Sorry about the delay. Could you update it to make it mergeable again?

**Comment by axelfontaine** [comment]
@anirudha13  Could you update this PR to make it mergeable again?

**Comment by axelfontaine** [comment]
Closing due to lack of response.

**Pull request closed without merging**
