### PR TITLE
Added support for Microsoft Parallel Data Warehouse and Non-Transactional DDL platforms

### LINKED ISSUE #1330: Microsoft Parallel Data Warehouse support
Add support for Microsoft Parallel Data Warehouse.  I had started with a simpler question on StackOverflow but I am realizing what is necessary is general support for Microsoft Parallel Data Warehouse.  I have started work on adding this support in my own fork but will need some guidance in order to complete it.  Happy to contribute my time or attempt to provide some sponsorship for the feature.

Here is a link to my ongoing work as I've been capturing on [StackOverflow](http://stackoverflow.com/questions/37501311/override-default-script-for-initialization-of-flyway-metadata-table).

### PR DESCRIPTION
**Pull request by fdefalco**
Created a CommercialDBSubsetTest profile in pom.xml since you can readily access the drivers for Microsoft SQL Server, Oracle, and DB2 but the SAP Hana driver seems inaccessible.

Added support for Microsoft Parallel Data Warehouse - closes #1330

Added a NonTransactionalTemplate class for those databases that do not support transactional DDL.  Only leveraging this class for SQL Server PDW currently.

Modified SqlMigrationExecutor to base executeInTransaction on dbSupport.

### CODE REVIEW

**Comment by axelfontaine** [comment]
Thanks for the pull request. Please remove all unnecessary formatting changes (this creates way too much noise to review this) as well as the non-transactional change. This will be implemented via auto-detection in 4.1.

**Comment by fdefalco** [comment]
Will do - is there a planned release timing for 4.1? I can hold off with this pull request until the new non-transactional support is available and then add the necessary files for Microsoft Parallel Data Warehouse if that makes sense.

**Comment by axelfontaine** [comment]
4.1 is just around the corner and the non-transactional support has been committed

**Comment by pik0** [comment]
Awesome!!

**Pull request closed without merging**
