### PR TITLE
Added Vertica 10_1 support

### PR DESCRIPTION
**Pull request by drachich**
Added Vertica 10.1 support. Used existing vertica_9_pr as starting point, improved, fixed some bugs and tested on newer Vertica version.

Tested for Vertica 10.1. 

I am in contact with Vertica team and if you need Docker for testing on testcontainers to accept this PR, you can contact me and we will try to come up with something, because official Docker container for Vertica will be released soon.

I am sure there are people waiting for Vertica support from Flyway, so I hope this PR can help them.

### CODE REVIEW

**Comment by MikielAgutu** [comment]
We do require an official Docker image before we can add support for a database. Can you provide us with a contact email so we can learn more about the Vertica Docker image?

**Comment by drachich** [comment]
Vertica released official Docker image few days ago!
Here it is:
https://github.com/vertica/vertica-kubernetes/blob/main/docker-vertica/Dockerfile

**Comment by MikielAgutu** [comment]
Thanks for the update - the new Docker image looks promising.

We'll re-consider Vertica support this year. We can't commit to a specific timeframe yet, but having a Docker image makes Vertica a more realistic prospect for inclusion to Flyway.

**Comment by drachich** [comment]
Vertica created new single-node Docker image that can be especially used in tests !
https://hub.docker.com/r/vertica/vertica-ce
Maybe we can continue and finalize Vertica's support? It is pretty widely used database, and I hope a lot of guys will thank us for supporting it!

**Comment by piers-williams** [comment]
Thank you for your submission. We cannot merge this at this time as it would need re-implementing in the [https://github.com/flyway/flyway-community-db-support](https://github.com/orgs/red-gate/projects/71/views/flyway-community-db-support) repository.

**Pull request closed without merging**
