### PR TITLE
Exasol support

### LINKED ISSUE #2018: Exasol 6.0.5 support
###### Which version and edition of Flyway are you using?

5.0.7

###### If this is not the latest version, can you reproduce the issue with the latest one as well?
(Many bugs are fixed in newer releases and upgrading will often resolve the issue)
Tried it....but no native support

###### Which client are you using? (Command-line, Java API, Maven plugin, Gradle plugin)
Command-line

###### Which database are you using (type & version)?
Exasol 6.0.5

###### Which operating system are you using?
Windows 10/Red Hat Linux

###### What did you do?
(Please include the content causing the issue, any relevant configuration settings, the SQL statement that failed (if relevant) and the command you ran.)
Used EXASOL_JDBC-6.0.5.jar but since Exasol is unsupported, flyway didnt work.

###### What did you expect to see?
Connection to Exasol natively from flyway component

###### What did you see instead?
ERROR: Unsupported Database: EXASolution 6.0

### PR DESCRIPTION
**Pull request by GordeevArt**
Add Exasol 6.0+ support

Resolves: https://github.com/flyway/flyway/issues/2018

### CODE REVIEW

**Comment by DavidGran** [comment]
hey there... i'm happy to see that there is an implementation to support exasol, but whats the state of this feature?

**Comment by GordeevArt** [comment]
I use this on production. Now I've resolve the conflicts.

**Comment by andyalbert** [comment]
Hello, is there any chance to merge this to master soon? :smile:

**Comment by allipatev** [comment]
Hey @GordeevArt ,
Have you thought about signing the license agreement mentioned in https://github.com/flyway/flyway/pull/2931#issuecomment-693197746 to push this PR further?

**Comment by ThomasBestfleisch** [comment]
@GordeevArt It would be really great if this could be merged, as a few other Exasol customers would love using this plugin

**Comment by mircea-lemnaru-aera** [comment]
It seems that @GordeevArt is not active anymore ? Maybe it's a good idea that we clone his changes and push the code further because for sure there are folks who could use this. 

Any idea how we should proceed ?

**Comment by GordeevArt** [comment]
Flyway don't want my changes 😿

**Comment by mircea-lemnaru-aera** [comment]
> Flyway don't want my changes 😿

Why do you say that ? :)

**Comment by piers-williams** [comment]
Thank you for your submission. We cannot merge this at this time as it would need re-implementing in the [https://github.com/flyway/flyway-community-db-support](https://github.com/orgs/red-gate/projects/71/views/flyway-community-db-support) repository.

**Comment by raayu83** [comment]
Any chance this will get implemented?
We will probably evaluate DB Migration Tools soon and Exasol support is important to us.

**Pull request closed without merging**
