### PR TITLE
Correct the feature name when cherry pick is set on community edition

### PR DESCRIPTION
**Pull request by wilkinsona**

### CODE REVIEW

**Comment by DoodleBobBuffPants** [comment]
Thanks for the PR! Please could you sign the CLA?

**Comment by wilkinsona** [comment]
Will do as soon as I've got the necessary approval. Hopefully that should be in the next few days.

**Comment by DoodleBobBuffPants** [comment]
As we want this to go out in the next release, we will be doing this ourselves and closing this PR, thanks though:)

**Comment by wilkinsona** [comment]
I totally understand and can only apologise for the delay. FWIW, I would have done the same thing in your situation.  The approval processes is a one-off and is almost complete so the small silver lining is that I will be able to sign the CLA shortly and any future contributions won't incur the same delay.

**Pull request closed without merging**
