### PR TITLE
TiDB Support

### PR DESCRIPTION
**Pull request by bb7133**

### CODE REVIEW

**Comment by wolf31o2** [comment]
Can you rebase this on current master?

**Comment by bb7133** [comment]
> Can you rebase this on current master?

@wolf31o2 Sure, I'll work on it.

**Comment by bb7133** [comment]
HI @wolf31o2 , I've updated the code, PTAL.

Thank you very much!

**Comment by bb7133** [comment]
Hello, @wolf31o2 , a friendly ping, would you check my code? thank you!

**Comment by wolf31o2** [comment]
This works fine. I've managed to forward port it to 7.1.1, but we still run into an issue on the foreign key checks. Waiting for that to be fixed in TiDB.

**Comment by wolf31o2** [comment]
I got this working on a 7.1.1 fork, using exactly one more commit. Since TiDB will always return 0 for the foreign key checks, rather than wait for upstream to fix the [issue](https://github.com/pingcap/tidb/issues/19449#issuecomment-680034456) related to the bad [return value](https://github.com/pingcap/tidb/issues/15131#issuecomment-611311153), I simply hard-coded the "correct" answer in [Flyway](https://github.com/ApplauseAQI/flyway/commit/1c524e648a59dd8997329bb759c19b220207993c#diff-5cecab9fc79b5a312ce277620874be90c30831340c6c9c0b692a05006f58160e) and migrations are working for me in TiDB.

**Comment by wolf31o2** [comment]
Here's my branch... https://github.com/ApplauseAQI/flyway/tree/PD-7410

I simply took your branch from here and rebased it on the 7.1.1 tag.

**Comment by coderplay** [comment]
@wolf31o2 Any updates on this PR?

**Comment by wolf31o2** [comment]
I'm using this in production. This PR needs to get my one patch applied, which is linked above. There's nothing left for me to do here. The PR author needs to update this branch.

**Comment by coderplay** [comment]
@bb7133 Would you please update your PR?

**Comment by bb7133** [comment]
@coderplay I've updated my PR, sorry for making it late!

**Comment by coderplay** [comment]
@wolf31o2 would you please stamp and merge?

**Comment by yijianli** [comment]
@wolf31o2 any updates?

**Comment by yijianli** [comment]
@juliahayward @axelfontaine  can you help to review this PR? thanks

**Comment by coderplay** [comment]
@juliahayward @DoodleBobBuffPants  @madninjaskillz could one of you please stamp it?

**Comment by juliahayward** [comment]
Can you point us to a freely available Docker image that we could use for testing?

( We're looking at overhauling the database support mechanism for v8 which will allow us to include support for databases that we're not explicitly testing, so the above won't be a constraint when we get there).

**Comment by coderplay** [comment]
@juliahayward  what did you mean by the docker image?  a TiDB image?

**Comment by bb7133** [comment]
> Can you point us to a freely available Docker image that we could use for testing?
> 
> ( We're looking at overhauling the database support mechanism for v8 which will allow us to include support for databases that we're not explicitly testing, so the above won't be a constraint when we get there).

Hi @juliahayward You can get the image of TiDB-server from https://hub.docker.com/r/pingcap/tidb/tags and start a standalone TiDB instance directly(the latest release `v5.0.2` is recommended):
```
docker run pingcap/tidb:v5.0.2
```
By default, TiDB listens to port `4000` and you can log in with the `root` account and an empty password. Please notice that this is a 'mock' cluster because it uses local storage('mocktikv'), but it should be OK for functional tests; for full cluster deployment, you can refer to [this document](https://docs.pingcap.com/tidb-in-kubernetes/stable/deploy-tidb-operator).

Sorry for replying late, please let me know if you have any further questions! /cc @coderplay

**Comment by juliahayward** [comment]
Great, thankyou! I've made a couple of changes to fit into our v8 codebase, which is due to ship later in the summer. Thankyou!

**Comment by DoodleBobBuffPants** [comment]
Closing as this will be available from the next release in [`flyway-community-db-support`](https://mvnrepository.com/artifact/org.flywaydb/flyway-community-db-support)

**Pull request closed without merging**
