### PR TITLE
Integrate a flyway-guice module

### PR DESCRIPTION
**Pull request by bfarka**
Since we are using flyway very often in combination with guice it would great to have a seperate module to provide guice integration out of the box..

I added a new sub project which is containing a guice module.
This module only needs a jdbc Datasource in the Injection Context and has the possibilty  to do the migration while binding Flyway to the DI - Context or a user can inject Flyway an call the migration manually...

### CODE REVIEW

**Comment by bfarka** [comment]
it seems there was a problem with travisCI...

on my repo the build went fine ..
but on the Pull Request on flayway it once got strange connection refused and on the other some test seemed to hang..

please retrigger it manually

**Comment by axelfontaine** [comment]
Thanks for the PR. I am currently unsure about integrating this in the main repo. Please maintain and document it in a separate repo for now (I can offer you one under the flyway organisation if you wish). If it proves successful I will gladly reconsider my position.

Cheers
Axel

**Comment by bfarka** [comment]
HI Axel

for me it would be fine if you could provide a repo for this module...

so you suggest, i'll publish the version side-by-side with flyway itselfe with a seperate name, and we will see how it gets used?

wbr
Bernd

**Comment by axelfontaine** [comment]
Yes. I've created a new flyway/flyway-guice repo and added you as a collaborator.

Cheers
Axel

**Pull request closed without merging**
