### PR TITLE
Fixed #1592: schema clean failed on DB2 z/OS with partitioned table space

### LINKED ISSUE #1592: schema clean fails on DB2 z/OS with sqlcode -669 rc 0001
###### What version of Flyway are you using?
4.1.2

###### Which client are you using? (Command-line, Java API, Maven plugin, Gradle plugin, SBT plugin, ANT tasks)
Java API, Command-line

###### What database are you using (type & version)?
DB2 z/OS V11

###### What operating system are you using?
z/OS

###### What did you do?
(Please include the content causing the issue, any relevant configuration settings, and the command you ran)
tried $flyway clean in the API version

###### What did you expect to see?
a cleaned up schema

###### What did you see instead?
-669   THE OBJECT CANNOT BE EXPLICITLY DROPPED. REASON reason-code
This because a table in an explicitly created tablespace cannot be explicitly dropped.

### PR DESCRIPTION
**Pull request by Muni10**

### CODE REVIEW

**Comment by Muni10** [comment]
Build failed due to missing AWS credentials (same as master)

**Comment by axelfontaine** [comment]
No actually it tries to pull in dependencies it shouldn't according to the configured Maven profiles. It's really weird. This only happens on Travis CI and I can't seem to figure out why.

**Comment by Muni10** [comment]
Could this be because it's using the maven wrapper shell that starts a Java command so it can't interpret the -P parameter? I know OpenJDK has support for -P as a propertyfile, but can't find anything similar in the HotSpot JVM. Hotspot usually ignores parameters it does not understand, have seen that with the -P parameter for example. Are the profiles being used anywhere earlier in the build?

**Comment by axelfontaine** [comment]
Closing as DB2 z/OS support has been discontinued in the main distribution.

**Pull request closed without merging**
