### PR TITLE
Use Spring ApplicationContext to resolve SpringJdbcMigrations

### PR DESCRIPTION
**Pull request by guylabs**
Pull request for #1062.

### CODE REVIEW

**Comment by reda-alaoui** [comment]
Hello,

Thank you for your PR.
I am currently trying to use it on my project.
But it seems that it doesn't manage spring proxies.

Indeed if we add ```@Transactional``` to our ```SpringJdbcMigration``` object, call to ```extractMigrationInfo``` fails.
I think it should pass the extracted bean proxied by Spring to ```extractMigrationInfo```.

Regards

**Comment by guylabs** [comment]
Hi @reda-alaoui,

why do you add `@Transactional` to your `SpringJdbcMigration`s? Because these migrations are executed inside a transaction created by Flyway.

Thanks and regards,

Guy

**Comment by wimdeblauwe** [comment]
I am trying to use this custom migrator in my own project. For this, I added `ApplicationContextAwareSpringJdbcMigrationResolver` in my own project until this will be released in Flyway itself. However, when using Flyway 4.0 (which I need to do to be able to disable the default MigrationResolvers), then the constructor is not valid. I needed to change it to:

    public ApplicationContextAwareSpringJdbcMigrationResolver(Scanner scanner, Location location, FlywayConfiguration configuration, ApplicationContext applicationContext) {
        super(scanner, location, configuration);
        this.applicationContext = applicationContext;
    }

**Comment by nbijl** [comment]
Can we also use that to make use of repositories in the migrations?

**Comment by wimdeblauwe** [comment]
I have used it with a Spring Data repository and it worked (for inserting
data). I did had to disable the hibernate ddl validation because it ran
before the flyway scripts.
Op vr 8 apr. 2016 om 09:38 schreef nbijl <notifications@github.com>

**Comment by guylabs** [comment]
Hi @wimdeblauwe,

thanks for the hint. I just updated the pull request, merged the master to the branch and upgraded the Spring dependency to the latest version.

Regards,

Guy

**Comment by alexparlett** [comment]
We found that there might be an issue with how this is done. If you keep the default migration resolvers and just use the application context aware one as a custom migration resolver then you cannot have the spring autowired and spring jdbc migrations in the classpath locations as the old spring jdbc migration resolver attempts to run the migrations as they have a base class of SpringJdbcMigration.

However if they arent on the flyway classpath and instead just use Springs autowiring to find them then you run into the issue that flyway is then unaware of all the migrations and may attempt to apply migrations in the wrong order. Ideally these shouldn't share the same base interface of SpringJdbcMigrations. We've made this change to our local version of flyway and are happy to provide a pr into either here or your fork Guy.

**Comment by guylabs** [comment]
Hi @alexparlett 

yes that is true. Thanks for pointing this out! Well could you create a PR into my fork such that we have everything together for this feature? That would be awesome.

Thanks and regards,

Guy

**Comment by geirgp** [comment]
What's the status on this PR? I want to inject Spring's Environment in order to have conditional flyway migrations for the purpose of enabling/disabling demo data.

**Comment by geirgp** [comment]
@wimdeblauwe How did you disable the default MigrationResolvers? I'm using Spring Boot..

**Comment by axelfontaine** [comment]
Thanks for the pull request. We have now implemented this differently. See https://github.com/flyway/flyway/issues/1062#issuecomment-446279678

**Pull request closed without merging**
