### PR TITLE
WIP: add support for migration timeout

### PR DESCRIPTION
**Pull request by mathieu-pousse**
Give a try to add support for migration timeout

### CODE REVIEW

**Comment by mathieu-pousse** [comment]
This is a first attempt to work on issue #887

The main drawback of this implementation is that we are forced to detach the migration on a separate Thread But as far as I can see, there is no other way in Java to timeout a callable.

Still need to polish and add some tests

Any remarks appreciated

**Comment by mathieu-pousse** [comment]
Dany idea who thé ci faibles? Pas it working encore m'y changes?

**Comment by mathieu-pousse** [comment]
@tjerkw personnaly, I don't especially need it anymore. 

We are also in a CD context and we cannot limit migrations by their execution delay.

What we ensure, is that the migration are run in a non blocking fashion, meaning the migration must not lock tables.
We also run the migrations before the application is actually deployed (this is mainly due to liveness probe from kubernetes)

With that, their is no reason to rollback any migration

**Comment by tjerkw** [comment]
But some postresql migastions such als "alter table" lock the table by
default. You can't get around it. How do you solve that. What if you can't
get a lock?

**Comment by MikielAgutu** [comment]
Is this still relevant? We've done some work to improve Postgres locking issues.

**Comment by DoodleBobBuffPants** [comment]
Closing until further activity

**Pull request closed without merging**
