### PR TITLE
Apache Phoenix support

### LINKED ISSUE #2112: Apache Phoenix support in Flyway 5.x
I see that Flyway 5.0 dropped support for Phoenix. I guess this was due to lack of interest in a fairly weird, niche DB. Looking at past issues it seems that Phoenix provides the necessary bits and pieces, although the Phoenix support in 4.x doesn't handle schemas.

### PR DESCRIPTION
**Pull request by smmckay**
Fixes #2112

### CODE REVIEW

**Comment by nycjay** [comment]
Is this still on target for 6.1?

**Comment by MikielAgutu** [comment]
Closing due to CLA not being signed

**Comment by nycjay** [comment]
@smmckay @dennislloydjr 
Any chance you guys could sign the CLA so we can get this changeset added in?

**Comment by smmckay** [comment]
I thought I had, must've forgotten.

**Comment by nycjay** [comment]
> I thought I had, must've forgotten.

Sweet. @MikielAgutu If the CLA gets signed, could we get this added back in? We have been managing our Phoenix migrations with Flyway for several years now.

**Comment by nycjay** [comment]
@dennislloydjr Any chance you could sign the CLA?

**Comment by nycjay** [comment]
@MikielAgutu What are our options here? It is still not clear why support for Phoenix was removed. How can we get it back?

**Pull request closed without merging**
