### PR TITLE
Resolve environment variables in configuration file

### PR DESCRIPTION
**Pull request by dsbert**
This change adds support for resolving environment variables in the configuration file for the command line tool. This is a pending feature request #1479

```
flyway.placeholders.somevar=${MYVAR}
```

While developing this update, I found an issue with the ant tests on my system and had to modify `ant/AbstractFlywayTaskSmallTest.java`. I'm building the project from the `D:` drive and this test was failing because `File.listRoots()[0].getPath();` would resolve to the `C:` drive.

### CODE REVIEW

**Comment by teddywilson** [comment]
@flyway Having this same issue and would love to see these changes roll out!

**Comment by yed30** [comment]
@flyway Same here for use in docker

**Comment by plemaire** [comment]
@flyway Same here. Would be nice to be able to use environment variables directly from the configuration file.

**Comment by vnbarr** [comment]
@flyway any update on when this PR will be merged? Is there any workaround for this issue? Thanks!

**Comment by dsbert** [comment]
@vnbarr 

It looks like since I created this pull request, the ability to load placeholders directly from environment variables was added.

https://flywaydb.org/documentation/envvars#FLYWAY_PLACEHOLDERS_

I still think it would be nice to support both since I would rather keep everything in one config file but I don't see any reason to bring this pull request back up to date if there's no chance of it getting merged.

**Comment by juliahayward** [comment]
Closing this pull request, as the author is not responding to requests to sign the CLA. #1479 will remain open and we are open to new pull requests!

**Pull request closed without merging**
