### PR TITLE
Databricks integration

### PR DESCRIPTION
**Pull request by tdimhcsleumas**
This is building off of @zayscue's change to bring databricks support to flyway. Databricks can either be configured to use the unity catalog or not, so this change allows one to use databricks without necessarily opting-in to the unity catalog. As far as I can tell, the main difference between using the unity catalog is the presence of the `information_schema`. Without unity, this does not exist and so the original implementation does not work for that use case. 

This change utilizes the `SHOW { TABLES | FUNCTIONS | VIEWS }` command in lieu of querying `information_schema` to introspect the status of a schema.

### CODE REVIEW

**Comment by Barry-RG** [comment]
@tdimhcsleumas and @zayscue if either of you are still interested in adding databricks to Flyway, could you please port this PR to https://github.com/flyway/flyway-community-db-support

**Comment by tdimhcsleumas** [comment]
Thanks for the heads up @Barry-RG. I'm beginning work on porting this change to the new repo.

**Comment by tdimhcsleumas** [comment]
https://github.com/flyway/flyway-community-db-support/pull/26

**Comment by Barry-RG** [comment]
Closing this here as it has been opened in https://github.com/flyway/flyway-community-db-support/pull/26

**Pull request closed without merging**
