### PR TITLE
Sybase ASE support

### PR DESCRIPTION
**Pull request by super132**
This is to address issue #102 feature request which to support Sybase. I can now only work and test on Sybase ASE and thus the changes here is to support Sybase ASE only.

Comments are highly welcomed.

### CODE REVIEW

**Comment by axelfontaine** [comment]
Hi Jason,

thanks for the PR. Please update to be mergeable. Also please provide a PR against flywaydb.org for the docs.

Cheers
Axel

**Comment by super132** [comment]
Hi Axel,

I have updated the codes with the latest codes in master branch, please have a check. I'll create another pull request to update the doc.

Thanks.

Sincerely,
Jason

**Comment by axelfontaine** [comment]
One thing is bothering me: why did you duplicate all test cases?

**Comment by super132** [comment]
That is because the script that used in the parent test cases cannot be used in Sybase ASE as it needs to use "GO" to be the delimiter but not semicolon. Also, it does not support schema and thus I duplicated a set of test cases out. If it is not a good approach then I could try modifying the base test cases to accept different test scripts paths for children cases to override.

**Comment by axelfontaine** [comment]
GO: Can't you use the same strategy as was used for MS SQL Server?

Schema: What do you mean by "it does not support schema"? The reference docs seem to contradict this: http://infocenter.sybase.com/help/index.jsp?topic=/com.sybase.infocenter.dc36272.1550/html/commands/X48762.htm

**Comment by axelfontaine** [comment]
Schema: hmm you are right, upon closer inspection their concept of a schema doesn't seem to match the way the rest of the industry sees this very much...

**Comment by super132** [comment]
Yes, I have checked some sources and then concluded that Sybase schema is not something like what we have in Oracle or MS SQL. The <schema_name>.<db_name> notation is not supported in Sybase ASE 12.5 (The only Sybase that I have access to). Therefore, is there any better way to reuse the testing SQL scripts but can drop out the schema notation?

**Comment by super132** [comment]
Axel, I will try refer to SQLite test cases as it does not support schema as well. Will update the PR.

**Comment by super132** [comment]
After checking with the test scripts. The test scripts delimited wtih semicolon cannot be accepted by Sybase ASE server. It seems like SQL server support semicolon as delimiter as well but not Sybase. I cannot find any delimiter conversion code in the test classes. Would you point me to the class or file if I missed something?

If duplicated SQL scripts are not preferred then I may look into writing conversion script to convert delimiter for testing.

**Comment by axelfontaine** [comment]
OK, then it probably makes indeed more sense to duplicate them.

**Comment by axelfontaine** [comment]
The plan now is to include this in 4.0 due in April. Can you make it mergeable again after 3.2 is out?

Thanks
Axel

**Comment by super132** [comment]
Hi Axel,

No problem. Please let me know when it is ready.

Thanks.
Jason

**Comment by mcai4gl2** [comment]
Hi Axel,

We are currently evaluating flyway internally and would like to roll it out for most of our teams. One feature gap raised by one of our team is Sybase support. Looking at this thread, can you please provide some information regarding the timeline for 4.0 release?

Thanks a lot.

Geng

**Comment by caledhwa** [comment]
Yes, also interested in this feature. Right now it's not mergeable. Can we get it mergeable and then added to master?

**Comment by super132** [comment]
@axelfontaine I have merged the codes with the latest revision in master. Please take a look. Thanks.

**Comment by PratikModi** [comment]
Any Update on when Flyway 4.0 will be released? Looking for forward to use Flyway with Sybase support. Please provide an update.

**Comment by PratikModi** [comment]
Any date for Flyway 4.0 Release ?

**Comment by axelfontaine** [comment]
Hi Jason,

Could you also add a pull request against the flyway-4.0 branch of flyway/flywaydb.org with a DB-specific page (like http://flywaydb.org/documentation/database/oracle.html) as well as details on how to set it up (http://flywaydb.org/contribute/code/database.html)?

I have been fighting last night to get Sybase (or SAP as it's now called) ASE 16 up and running without success on my Win 10 x64 machine.

Once those are through we should be OK for a speedy merge.

Cheers
Axel

**Comment by super132** [comment]
Hi @axelfontaine ,

I will try to make the PR this week. Sorry for the late response.

Thanks.

Jason

**Comment by super132** [comment]
Hi Axel,

I have submitted the PR against `flyway-4.0` branch in `flywaydb.org` repository. Please take a look. 

Thanks.

**Comment by axelfontaine** [comment]
Thanks! Merged.

**Comment by axelfontaine** [comment]
@super132 Could you please contact me by email at axel at boxfuse dot com ? Thanks!

**Pull request merged**
