### PR TITLE
always check that the lock was released

### PR DESCRIPTION
**Pull request by snopoke**
Leaving the lock in place can cause problems when using flyway from multiple processes or across multiple machines. It is also very hard to debug. This PR checks that the lock is actually released and if not outputs an error log.

An example of how this might happen: https://github.com/flyway/flyway/issues/2895

### CODE REVIEW

**Comment by snopoke** [comment]
> [CLA assistant check](https://cla-assistant.io/flyway/flyway?pullRequest=3054)
> Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/flyway/flyway?pullRequest=3054) before we can accept your contribution.
> You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/flyway/flyway?pullRequest=3054) it.

I'm not willing to provide access to all these permissions:

image

**Comment by DoodleBobBuffPants** [comment]
Could you try the following link? https://cla-assistant.io/flyway/flyway

**Comment by snopoke** [comment]
> Could you try the following link? https://cla-assistant.io/flyway/flyway

Done, thanks.

**Comment by Rixium** [comment]
Thanks for the PR, and welcome to the [Hall of Fame](https://flywaydb.org/documentation/contribute/hallOfFame). 🎉

We've just reimplemented this in the next release.

**Pull request closed without merging**
