### PR TITLE
Searches all dex files for migrations

### PR DESCRIPTION
**Pull request by TomRK1089**
While most apps will have a single dex file with all classes, some applications will leverage the MultiDex solution provided by the support library (and on later VMs supported natively). We need to scan these secondary dex files for migrations as well, as most authors will not manually ensure that their Java migrations are located in the "primary" dex file.

### CODE REVIEW

**Comment by axelfontaine** [comment]
Thanks for the pull request. This seams to be creating a bunch of temp files. Are they automatically being cleaned up as well?

**Comment by TomRK1089** [comment]
@axelfontaine good point. The files are being written into the application's cache directory but we ought to clean them up after the classes themselves are scanned and loaded. I can make some changes.

**Comment by axelfontaine** [comment]
Can you clean this up so it can be merged?

**Comment by TomRK1089** [comment]
@axelfontaine can do.

**Comment by TomRK1089** [comment]
@axelfontaine This may be a world record for stale PRs, but I've rebased and updated these changes to work with Flyway 5.0, as well as added the temp file cleanup previously mentioned. The change had dropped off of our radar since the project that ran into this entered maintenance mode.

**Comment by MikielAgutu** [comment]
Is this still relevant? As I understand Flyway's Android support is in a bad way due to a third party driver being broken (https://github.com/flyway/flyway/issues/970#issuecomment-542695204)

**Comment by DoodleBobBuffPants** [comment]
Closing until further activity

**Pull request closed without merging**
