### PR TITLE
Yet another ClickHouse support

### PR DESCRIPTION
**Pull request by a-konyaev**
Based on #2166 and #1773 
This one has some improvements in comparison to previous implementations:
- more accurate declaration of the schema table's columns (types and default values)
- "baseline" supporting
- "repair" supporting. ClickHouse does not allow DELETE and UPDATE statements so this implemented via executing several statements which do copying only those rows of the table that satisfy the condition into the newly created table followed by deletion of the previous table.
But this is a partial supporting - only for deleting failed migrations, not for updating migrations (description, checksum, etc).

### CODE REVIEW

**Comment by a-konyaev** [comment]
> [CLA assistant check](https://cla-assistant.io/flyway/flyway?pullRequest=2640)
> Thank you for your submission, we really appreciate it. Like many open source projects, we ask that you all sign our [Contributor License Agreement](https://cla-assistant.io/flyway/flyway?pullRequest=2640) before we can accept your contribution.
> **1** out of **2** committers have signed the CLA.
> 
> ✅ a-konyaev
> ❌ Alexey Konyaev
> 
> **Alexey Konyaev** seems not to be a GitHub user. You need a GitHub account to be able to sign the CLA. If you have already a GitHub account, please [add the email address used for this commit to your account](https://help.github.com/articles/why-are-my-commits-linked-to-the-wrong-user/#commits-are-not-linked-to-any-user).
> You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/flyway/flyway?pullRequest=2640) it.

image
I have signed already...

**Comment by reds7373** [comment]
Can you let me know what is the ETA for merging this PR to support Clickhouse from FlywayDB

**Comment by MikielAgutu** [comment]
@reds7373 We haven't committed to adding ClickHouse support. [See our policy on adding DB support to Flyway](https://flywaydb.org/documentation/contribute/contributingDatabaseSupport#why-doesnt-flyway-accept-all-database-support-contributions).

[It's on our radar](https://github.com/flyway/flyway/issues/1772). We regularly review requests for DB engine support. If ClickHouse becomes more popular, both in [DB engine ranking](https://db-engines.com/en/ranking), and with the Flyway community, we may give it higher priority.

**Comment by a-konyaev** [comment]
Hi guys! I have actualized the PR changes to resolve conflicts with the master branch.
BTW, in our community (https://t.me/clickhouse_ru, 4К+ members) people are constantly interested in a migration tool for Clickhouse DB. This PR is one of possible solution. But you, unfortunately, ignore it.
ClickHouse has become much more popular over the past year: https://db-engines.com/en/ranking_trend/system/ClickHouse
Maybe it's time to decide to include it in the master? ;)

**Comment by jondeandres** [comment]
Any update on this?

**Comment by DoodleBobBuffPants** [comment]
Closing duplicate database support PR, see https://github.com/flyway/flyway/pull/2981

**Pull request closed without merging**
