### PR TITLE
Add support for the Redshift-specific JDBC driver

### PR DESCRIPTION
**Pull request by nathanvick**
Proposed implementation #1058, using detectDriverForUrl for the JDBC 4.1 driver and detectBackupDriverForUrl for JDBC 4 driver. I also had to fix a couple of bugs along the way to make the tests pass.

### CODE REVIEW

**Comment by axelfontaine** [comment]
Awesome work Nathan! Truly appreciated!

**Comment by nathanvick** [comment]
@axelfontaine,

I added some more fixes, to make the tests pass if using the Redshift JDBC driver. The Redshift tests now work with either the PostgreSQL driver or the Redshift driver.

**Comment by nathanvick** [comment]
@axelfontaine,

I think these last two commits should be integrated into flyway 4.

**Comment by axelfontaine** [comment]
Thank you very much Nathan! Merged.

**Pull request merged**
