### PR TITLE
Flyway 5.0 Crash on Android

### PR DESCRIPTION
**Pull request by benoitdevos**
When upgrading an existing Android app from Flyway 4.2 to 5.0.7, Flyway crashes with the following stack trace:
```
    Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'int java.lang.String.indexOf(java.lang.String)' on a null object reference
        at org.flywaydb.core.internal.database.DatabaseFactory.filterUrl(DatabaseFactory.java:204)
        at org.flywaydb.core.internal.database.DatabaseFactory.getJdbcUrl(DatabaseFactory.java:191)
        at org.flywaydb.core.internal.database.DatabaseFactory.createDatabase(DatabaseFactory.java:72)
        at org.flywaydb.core.Flyway.execute(Flyway.java:1634)
        at org.flywaydb.core.Flyway.info(Flyway.java:1321)
```
This is caused by `connection.getMetaData().getURL()` returning `null` when using SQLite and SQLDroidDriver as recommended. This is fixed in [this commit](../commit/545fd46c8dde422276e2f2215e3e1311a973c17d).

When fixed, another problem occurs:  Flyway complains that the SQLite version has to be at least 3.7.2, which:

- was not true with Flyway 4.
- is not compliant which [documentation on SQLite on Android](https://flywaydb.org/documentation/database/sqlite).

This is fixed in the [second commit](../commit/abc699d50f34cf6075d83c2d9a4cc559a19f6a7d).

Both these commits make Flyway working just fine on Android with SQLite and SQLDroidDriver.

### CODE REVIEW

**Comment by axelfontaine** [comment]
Thanks for the pull request. This is actually pretty frustrating as both of these issues are SQLDroid issues. And to add insult to injury they have already been fixed ages ago as well! All that is missing is a SQLDroid release. See https://github.com/SQLDroid/SQLDroid/issues/71

**Comment by benoitdevos** [comment]
@axelfontaine Sorry I just wanted to provide a patch that let Flyway and Android enthusiasts to seamlessly  migrate to version 5, but wording of this PR was not adequate. I do agree that this is a work around SQLDroid "weakness".
I will consider pushing an official fork of SQLDroid...

**Comment by axelfontaine** [comment]
No need to be sorry. I am frustrated with SQLDroid, not with your pull request :-)

**Comment by axelfontaine** [comment]
Closing as the null check has been implemented as part of a different commit. See https://github.com/flyway/flyway/blob/master/flyway-core/src/main/java/org/flywaydb/core/internal/database/DatabaseFactory.java#L226

**Pull request closed without merging**
