### PR TITLE
Add Firebird support

### PR DESCRIPTION
**Pull request by mrotteveel**
This adds Firebird support for Firebird 2.1 - Firebird 3.0 (upcoming Firebird 4 should work as well). This could replace #1889.

Let me know if you need more changes, or if you need more information.

Accompanying documentation changes in https://github.com/flyway/flywaydb.org/pull/117

### CODE REVIEW

**Comment by staabm** [comment]
we are also interessted in Firebird 2.5 support. would be great to have.

**Comment by alextercete** [comment]
Thank you @mrotteveel for your contribution, this will be released with Flyway 6.0.0. 🙏

**Comment by alextercete** [comment]
@mrotteveel There seems to have been a small change in the CLA, would you mind resigning it, please? Thanks!

**Comment by mrotteveel** [comment]
@alextercete I signed the CLA again

**Pull request merged**
