### PR TITLE
Clickhouse replicated

### PR DESCRIPTION
**Pull request by bennyhils**

### CODE REVIEW

**Comment by rleibman** [comment]
Any updates on when this is coming in?

**Comment by shea-hawkins** [comment]
@DoodleBobBuffPants -- we're looking to begin using this. Other than the new merge conflicts, what do you think it will take to get this approved?

**Comment by eugene-bright** [comment]
@a-konyaev Hi!
Do you have plans to sign CLA and make this code to be merged?

**Comment by a-konyaev** [comment]
> @a-konyaev Hi!
> Do you have plans to sign CLA and make this code to be merged?
Hi!
I do not know how to do that :(
I guess this is some kind of bug on github - I signed CLA but it shows another user without CLA:
image

**Comment by eugene-bright** [comment]
> I do not know how to do that :(
> I guess this is some kind of bug on github - I signed CLA but it shows another user without CLA:

It looks like commit `Author` field must be more consistent. Now I see in the log this

```
commit ccc0955312f2dc2012146a770885e7d032e638a1
Merge: 7d33770aa 0e53d1cdc
Author: Alexey Konyaev <akonyaev@gmail.com>
...

commit 0e53d1cdcc109d660d41f390e353a5f5ad5015fd
Author: akonyaev <akonyaev@gmail.com>
...
```

[This instruction][git-author-change] shows how to rewrite history

[git-author-change]: https://www.git-tower.com/learn/git/faq/change-author-name-email/

**Comment by drriguz** [comment]
Any updates?

**Comment by sazonov** [comment]
I created a new PR for this feature https://github.com/flyway/flyway/pull/3611. It also meets current contribution rules.

**Comment by Barry-RG** [comment]
Clickhouse has been added via subsequent PRs

**Pull request closed without merging**
