### PR TITLE
#918 : Implementing explicit VIEW drop for PostgreSQL

### PR DESCRIPTION
**Pull request by gergelyszakacs**
- Created the abstract View class (a slight modification of Table)
- Created the PostgreSQLView class as an implementation
- Modified the Schema class to have View[] allViews() and View[] doAllViews()
- Modified the PostgreSQLSchema class to implement View[] doAllViews()
- Modified the rest of the vendor specific Schema classes to have a dummy impl

### CODE REVIEW

**Comment by axelfontaine** [comment]
Thanks for the pull request.

I currently see two issues here:
- lots of unnecessary reformating
- the view abstraction

Could you resubmit it with introducing both of the above?

Thanks
Axel

**Comment by gergelyszakacs** [comment]
Hi Axel,

Reformatting: no problem, I was using Eclipse. I install ItelliJ IDEA and
redo without formatting.
View abstraction: I'm not sure I understand what's wrong with it.


--
Gergő

**Comment by axelfontaine** [comment]
I'm fine fine with the view abstraction, but then all implementing classes should correctly be changed to use it (shouldn't be that much work though).

Looking forward to the update!
Axel

**Comment by axelfontaine** [comment]
Superseded by most recent commit. Closing.

**Pull request closed without merging**
