### PR TITLE
PostgreSQL: Filter functions and views from extensions during clean.

### LINKED ISSUE #100: Clean tries to drop a function from an extension and fails
_Original author: Martin.A...@gmail.com (May 11, 2012 10:11:31)_

We are using PostgreSQL 9.1 and are using the uuid-ossp extension. Clean tries to drop one of its functions. The extension has been installed manually as it required adding binaries to the DBMS.

Any way to work around this?

FlywayException: Error executing statement at line 64: DROP FUNCTION IF EXISTS &quot;public&quot;.&quot;uuid_nil&quot;() CASCADE
Occured in com.googlecode.flyway.core.migration.sql.SqlStatement in method execute, line number 78
Caused by org.postgresql.util.PSQLException: ERROR: cannot drop function uuid_nil() because extension uuid-ossp requires it
  Hint: You can drop extension uuid-ossp instead.
Occured in org.postgresql.core.v3.QueryExecutorImpl in method receiveErrorResponse, line number 2102

_Original issue: http://code.google.com/p/flyway/issues/detail?id=257_

### PR DESCRIPTION
**Pull request by murdos**
This is an attempt to fix #100. 
As suggested in https://github.com/flyway/flyway/issues/100#issuecomment-65369658 the pg_depend view has been used to exclude views and functions that are depend on an extension.
The only thing I'm uncomfortable with is the handling of the allTypes() dropping.
Indeed all views and functions previously skipped and included in the final allTypes() dropping. I'm proposing to transform the dropping exception into a warning, as I don't see another way to handle the situation.

### CODE REVIEW

**Comment by axelfontaine** [comment]
Thanks for this. Couldn't the types be excluded using the same  pg_depend  mechanism?

**Comment by murdos** [comment]
Ok, so I tried to understand what was the purpose of **allTypes()** in the specific context of PostgresSQL. My conclusion is that the PostgreSQL implementation of **DatabaseMetaData.getUDTs()** returns all types of type *'composite'* (automatically created for each table or view to represent the row structure of the table) and *'domain'*.
Since the PostgreSQLSchema already cleans base types, enums, domains and tables, I really wonder what is the purpose of the ending allTypes() dropping since it just overlaps with previous cleaning. Is there's a specific reason for its introduction?
I suggest to just remove this ending dropping using allTypes().

BTW the current patch doesn't work since the raised SQLException rollbacks the transaction.

**Comment by murdos** [comment]
Patch updated.

**Comment by axelfontaine** [comment]
Are there any remaining issues with this?

**Comment by murdos** [comment]
I don't think so.

**Comment by axelfontaine** [comment]
No good. This immediately caused tests to fail in the test suite on my machine. No idea why this passed on Travis, but this fails for me with

```
Tests run: 47, Failures: 0, Errors: 1, Skipped: 1, Time elapsed: 16.507 sec <<< FAILURE! - in org.flywaydb.core.internal.dbsupport.postgresql.PostgreSQLMigrationMediu
mTest
type(org.flywaydb.core.internal.dbsupport.postgresql.PostgreSQLMigrationMediumTest)  Time elapsed: 0.32 sec  <<< ERROR!
org.flywaydb.core.internal.dbsupport.FlywaySqlScriptException:
Migration V1__Type.sql failed
-----------------------------
SQL State  : 42710
Error Code : 0
Message    : FEHLER: Typ ╗my_type½ existiert bereits
Location   : migration/dbsupport/postgresql/sql/type/V1__Type.sql (C:\Workspaces\flyway\flyway-core\target\test-classes\migration\dbsupport\postgresql\sql\type\V1__Ty
pe.sql)
Line       : 17
Statement  : CREATE TYPE my_type AS (my_type_id integer)

        at org.postgresql.core.v3.QueryExecutorImpl.receiveErrorResponse(QueryExecutorImpl.java:2198)
        at org.postgresql.core.v3.QueryExecutorImpl.processResults(QueryExecutorImpl.java:1927)
        at org.postgresql.core.v3.QueryExecutorImpl.execute(QueryExecutorImpl.java:255)
        at org.postgresql.jdbc2.AbstractJdbc2Statement.execute(AbstractJdbc2Statement.java:561)
        at org.postgresql.jdbc2.AbstractJdbc2Statement.executeWithFlags(AbstractJdbc2Statement.java:405)
        at org.postgresql.jdbc2.AbstractJdbc2Statement.execute(AbstractJdbc2Statement.java:397)
        at org.flywaydb.core.internal.dbsupport.JdbcTemplate.executeStatement(JdbcTemplate.java:238)
        at org.flywaydb.core.internal.dbsupport.SqlScript.execute(SqlScript.java:114)
        at org.flywaydb.core.internal.resolver.sql.SqlMigrationExecutor.execute(SqlMigrationExecutor.java:71)
        at org.flywaydb.core.internal.command.DbMigrate.doMigrate(DbMigrate.java:345)
        at org.flywaydb.core.internal.command.DbMigrate.access$1000(DbMigrate.java:47)
        at org.flywaydb.core.internal.command.DbMigrate$4.doInTransaction(DbMigrate.java:301)
        at org.flywaydb.core.internal.util.jdbc.TransactionTemplate.execute(TransactionTemplate.java:72)
        at org.flywaydb.core.internal.command.DbMigrate.applyMigration(DbMigrate.java:298)
        at org.flywaydb.core.internal.command.DbMigrate.access$900(DbMigrate.java:47)
        at org.flywaydb.core.internal.command.DbMigrate$2.doInTransaction(DbMigrate.java:223)
        at org.flywaydb.core.internal.command.DbMigrate$2.doInTransaction(DbMigrate.java:166)
        at org.flywaydb.core.internal.util.jdbc.TransactionTemplate.execute(TransactionTemplate.java:72)
        at org.flywaydb.core.internal.command.DbMigrate.migrate(DbMigrate.java:166)
        at org.flywaydb.core.Flyway$1.execute(Flyway.java:861)
        at org.flywaydb.core.Flyway$1.execute(Flyway.java:818)
        at org.flywaydb.core.Flyway.execute(Flyway.java:1252)
        at org.flywaydb.core.Flyway.migrate(Flyway.java:818)
        at org.flywaydb.core.internal.dbsupport.postgresql.PostgreSQLMigrationMediumTest.type(PostgreSQLMigrationMediumTest.java:75)
```

Reverted.

**Comment by murdos** [comment]
Tests fixed. New PR: #1190

**Pull request merged**
