### PR TITLE
Added support for DB2 on AS/400 or ISeries

### PR DESCRIPTION
**Pull request by donnet**
First push of the modified version of the DB2as400 package

NB: the metadata table must be uppercase or the Table.exists() method won't find it
(perhaps a bug in the JTOPEN JDBC driver ?)

So for instance:
flyway.table=MY_SCHEMA

### CODE REVIEW

**Comment by axelfontaine** [comment]
This PR needs some cleanup before it can be merged:

- remove unnecessary reformatting of existing code
- remove code that is commented out
- add MigrationMediumTest + Concurrent test classes
- remove stdout printlns
- reevaluate the need for "constantitis" in the DB support class
- add a maven profile (excluded by default) to include the jdbc driver and run the tests
- provide a pull request against flywaydb.org with the documentation changes

Cheers
Axel

**Comment by mdeinum** [comment]
Any progress on this? I'm in need for as400 support. Can I help in improving this pull request?

**Comment by rotatomel** [comment]
Yes, As far as I tested it is working, if you download and apply the patch
of the pull request you can use flyway on as400. I need to create some test
and maybe a new profile because the tests will not be able to run on
Travis...

Regards!

2015-01-26 11:52 GMT-03:00 Marten Deinum <notifications@github.com>:

> Any progress on this? I'm in need for as400 support. Can I help in
> improving this pull request?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/flyway/flyway/pull/864#issuecomment-71471865>.
>



-- 
Rodrigo M. Tato Rothamel

**Comment by axelfontaine** [comment]
Any news on the points I mentioned?

**Comment by axelfontaine** [comment]
Closing due to lack of response.

**Pull request closed without merging**
