### PR TITLE
Updated table space for meta table, with db2 z/OS standard values

### PR DESCRIPTION
**Pull request by cteig**
Hi, 

The pull request contains changes in meta data table. Encoding is changed to EBCDIC, the standard for zOS, and the tablespace are updated with more standard values. 

Hope to reach the 4.0 release!

Christine

### CODE REVIEW

**Comment by axelfontaine** [comment]
Hi Christine,

Can you provide a smooth migration path for existing users (#1117) that migrates the encoding for them?

Best regards,
Axel

**Comment by cteig** [comment]
Hi

I have looked at updateMetaDataTable.sql for db2zos. I don´t think "call ADMIN_CMD" is something we can use. I have changed job and have no test environment anymore.  But I know someone who can test and change the new version, but we need a day or two. We will also look at a migration path, but I´m not sure if we need it. Maybe I will remove the encoding from the create table statement, and instead use the encoding scheme of the database. 

Christine

**Comment by axelfontaine** [comment]
Yes, I think simply using the encoding of the DB is probably the best option.

I simply copied the regular DB2 update file, so no worries about call ADMIN_CMD. All I care about is that the test passes :-)

**Comment by axelfontaine** [comment]
@cteig Did you make progress on this?

**Comment by cteig** [comment]
I have an appointment with someone with a test-environment tomorrow. 
The upgrade was not so easy as we first assumed. It has to work with the db2 z/os version 9 and newer
It is not possible to delete columns in version 9 :-(

Christine

**Comment by axelfontaine** [comment]
No worries Christine, if it doesn't work we'll simply instruct users to drop the table and recreate it with Flyway.baseline()

**Comment by cteig** [comment]
Hi

The issue is now handed over to a former colleague. You will get a pull request for this change, but I can´t say when. Mayby for a later release.

Christine

**Comment by axelfontaine** [comment]
Obsolete. Closing.

**Pull request closed without merging**
