### PR TITLE
Apache Hive support #142

### LINKED ISSUE #142: Hadoop Hive support
_Original author: christia...@gmail.com (October 28, 2011 20:18:52)_

Database support for Hadoop Hive

_Original issue: http://code.google.com/p/flyway/issues/detail?id=172_

### PR DESCRIPTION
**Pull request by mikaelv**
Resolves #142

All the tests in HiveMigrationTestCase pass.
The default HiveDriver throws UnsupportedOperationException all over the place.
I had to wrap the Driver and override some methods.

I cannot seem to run the HiveMigrationTestCase with maven without specifying the test explicitly with -Dtest
Could someone please review the pom.xml and let me know what command to run.

### CODE REVIEW

**Comment by wilderrodrigues** [comment]
Hi there,

I really need this feature.

I will fix the conflicts and update the PR. What is the chance this will get merged?

**Comment by axelfontaine** [comment]
@wilderrodrigues For this to be merged:
- all conflicts must be resolved
- all contributors must have signed the CLA
- all versions of Hive this has been tested against must be specified
- all Docker images representing those hive versions must be listed along with the exact settings used to start them to be able to test this

**Comment by nycjay** [comment]
@wilderrodrigues any update on this Hive support?

**Comment by piers-williams** [comment]
Thank you for your submission. We cannot merge this at this time as it would need re-implementing in the [https://github.com/flyway/flyway-community-db-support](https://github.com/orgs/red-gate/projects/71/views/flyway-community-db-support) repository.

**Pull request closed without merging**
