### PR TITLE
Fix for snowflake syntax handling errors 

### PR DESCRIPTION
**Pull request by niegowic**
Some key words were not added as CONDITIONALLY CREATED OBJECTS

### CODE REVIEW

**Comment by niegowic** [comment]
List build based on https://docs.snowflake.com/en/sql-reference/sql-all.html

Seems "COLUMN", "CONSTRAINT", "INDEX" won't be needed but didn't delete them

**Comment by niegowic** [comment]
@DoodleBobBuffPants  can you please review?

**Comment by DoodleBobBuffPants** [comment]
Hi @niegowic

Apologies but I've moved on to a different project, however I've forwarded this to the relevant team internally to look at :) 

And thanks for the PR!

**Comment by tjs145** [comment]
@niegowic just letting you know, we have been aware of this PR and we're just fixing some problems with our internal Snowflake testing pipeline. Once that's done we can get these changes released. Sorry for the delay.

**Comment by tjs145** [comment]
These changes have now been released

https://github.com/flyway/flyway/blob/main/flyway-core/src/main/java/org/flywaydb/core/internal/database/snowflake/SnowflakeParser.java#L30-L33

**Pull request closed without merging**
