### PR TITLE
Mongo migration

### PR DESCRIPTION
**Pull request by khatkar**
Mongo migrations (#810) for flyway are here! Specify migrations using the `db.runCommand` in javascript files. You can also write mongo migrations in java class. Please refer to flyway-sample-mongodb project for a quick example.

### CODE REVIEW

**Comment by nedkoh** [comment]
Is there a timeline for the merge and subsequent release?

**Comment by khatkar** [comment]
@nedkoh Not sure when this PR will be merged. If you don't want to wait, you can use the Mongo feature [here](https://github.com/risksense/flyway/tree/release-4.0.3-mongodb).

**Comment by stalniy** [comment]
@khatkar any chance that you will update this PR. Can I help you somehow to speed up merge?

**Comment by khatkar** [comment]
@stalniy I will update this PR in couple of days.

**Comment by stalniy** [comment]
@axelfontaine is there anything what delays this PR?

**Comment by oltoko** [comment]
Could anybody tell if this PR will be merged someday? I'm really waiting for this. Maybe their are some reason why this isn't still merged.
Any progress, even a discussion, would be nice!

**Comment by agardou** [comment]
same here, it would be really useful...

**Comment by khatkar** [comment]
Closing because I'm no longer able to maintain this.

**Pull request closed without merging**
