### PR TITLE
flyway.target=current will ignore all pending and future migrations when validating

### PR DESCRIPTION
**Pull request by sanjayd**

### CODE REVIEW

**Comment by axelfontaine** [comment]
Thanks for the pull request! Looks good.

Could you also post a PR against the flyway-3.2 branch of flywaydb.org with an updated description for flyway.target at all relevant places?

Cheers
Axel

**Comment by axelfontaine** [comment]
Could you also extend the test to prove it works as expected for migrate too (no-op)?

**Comment by sanjayd** [comment]
No problem - updated this PR and added PR #36 in flywaydb.org

**Comment by axelfontaine** [comment]
Merged. There turned out to be quite a few more places where the docs needed updating. I also slightly reworded the description.

Cheers,
Axel

**Pull request merged**
